---
- hosts: stats_node
  become: yes
  vars:
    influxdb_url: "https://dl.influxdata.com/influxdb/releases/influxdb-1.7.1.x86_64.rpm"
    app_node1_private: 172.31.30.193
    app_node2_private: 172.31.30.2
  tasks:
    - include_tasks: tasks/configure-databases.yml
    
- hosts: app_node1
  become: yes
  vars:
    telegraf_url: "https://dl.influxdata.com/telegraf/releases/telegraf-1.8.3-1.x86_64.rpm"
    db_node: 
  tasks:
    - include_tasks: tasks/configure-app-node.yml
    - include_tasks: tasks/configure-telegraf-appnode1.yml

- hosts: app_node2
  become: yes
  vars:
    telegraf_url: "https://dl.influxdata.com/telegraf/releases/telegraf-1.8.3-1.x86_64.rpm"
    db_node: 
  tasks:
    - include_tasks: tasks/configure-app-node.yml
    - include_tasks: tasks/configure-telegraf-appnode2.yml

