- name: "Install EPEL repository"
  yum:
    name: https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm
    state: present
- name: "Install nginx"
  yum:
    name: nginx
    state: present
- name: "Install cert-bot"
  yum:
    name: python2-certbot-nginx
    state: present
- name: "Setup load balanced proxy"
  template:
    src: templates/myproxy.conf
    dest: /etc/nginx/conf.d/nginx.conf
- name: "Setup letsencrypt"
  shell: certbot -i nginx -d "mtopoladsk.ml" --nginx -m "coldcash14@gmail.com" --agree-tos --redirect --no-eff-email
- name: "Free the port"
  shell: fuser -k 80/tcp
- name: "Restart nginx"
  service:
    name: nginx
    state: restarted